{% set name = "celer" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/celer-{{ version }}.tar.gz
  sha256: 2e3e65b5218eb2455155f3c54d2c6b33b486fd113b67fbe1f31723fe1ec14363

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython >=0.26
    - numpy
    - scipy >=0.18.0
    - scikit-learn >=1.0
  run:
    - python
    - download
    - libsvmdata >=0.3
    - matplotlib-base >=2.0.0
    - seaborn >=0.7
    - scikit-learn >=1.0
    - tqdm
    - xarray

test:
  imports:
    - celer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://mathurinm.github.io/celer
  dev_url: https://github.com/mathurinm/celer
  summary: Fast algorithm with dual extrapolation for sparse problems
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfansler
